version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8000:80"
    networks: 
      - application

networks: 
  application:
    driver: bridge
# volumes:
#   dbdata:
#     driver: local